### ISSUE TITLE
USER STORY : About Page

### ISSUE THREAD

**Issue by FerchaPombo** [FerchaPombo/userstoriesforproject4#18]
As a  site user, 
I can navigate to the About Page easily
So that I can access information about the page, and the people who created it 

### Acceptance Criteria
1. More  information about the developer and the webpage.
2. Section about the purpose of the page and experience of the developer

### Tasks

- [x] Write the content
- [x] Fromat the page 
- [x] Add necesary images
