### ISSUE TITLE
USER STORY  Profile Page

### ISSUE THREAD

**Issue by FerchaPombo** [FerchaPombo/userstoriesforproject4#19]
As a site user, 
I can access my profile page from the navbar 
So that I can see how my profile page looks.

### Aceptance Criteria 
1. User needs to be logged in to see their profile
2. If they dont upload any image there is a placeholder image to fill out the profile pic 
3. The profile includes the users links to social media

### Tasks 

- [x] Add conditionals to verify users authentification 
- [x] Add anker links to their social media that open in a new page 
- [x] Set a placeholder avatar image for the profile picture if no image uploaded
