### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by FerchaPombo** [FerchaPombo/userstoriesforproject4#21]
As a site user, 
I can use my username and password 
So that i can access my user account.

### Acceptance Criteria 

1. Users are directed to the 'Login' page when clicking the link on the navbar
2. Users can also login through the link in the registration form .
3. Users can also login  if they want to comment a post throgh a link on the comment box.
4. After login, users are redirected to the home page

### Tasks 

- [x] Conect the 'login' URL template to the navbar 
- [x] Add conditionals to show 'logout', 'dashboard and 'profile' links when user is logged in .
- [x] Adjust the sign in template from allauth.
