### ISSUE TITLE
USER STORY : Registration

### ISSUE THREAD

**Issue by FerchaPombo** [FerchaPombo/userstoriesforproject4#22]
As a site user, 
I can create an account when clicking the Register link in navbar 
So that i can also create content and engage with other users.

### Acceptance Criteria 
1. New users are directed to the registration form when clicking on the nav bar item. 
2. From has the necesary fields for registering and account.
3. After clicking the Submit button, users are redirected to the home page. 

### Tasks 

- [x] install Django Allauth and configure setting.py
- [x] Connect urls 
- [x] Modify signup template 
- [x] Add conditional statement to make link disapear from navbar when user logged in
