### ISSUE TITLE
USER STORY : About

### ISSUE THREAD

**Issue by FerchaPombo** [FerchaPombo/userstoriesforproject4#30]
As a site user, 
I can learn about the blog and the people who created it,
So that I feel connected to the blog. 

### Acceptance Criteria 

1. About section  that talks about the blog and the creator 
2. An image of the Cresator
3. Easy to reach about section through the navbar 

### Tasks 

- [x] Write the about section 
- [x] upload a profile pic 
- [x] Create the MVT for the section and link the Urls
